name = "Commandless"
author = "codeNredstone"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52bfd724b22ae9f148467cf543f5bca3c4ef7cc5302f54fb6ec0a02064124be3"

[versions]
fabric = "0.18.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-directory = "datapacks"
