name = "Commandless"
author = "codeNredstone"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65abd407b556ab98c2ae232e4716aee4b1143e86e1b9a7a471ddf7d260ce5ce0"

[versions]
fabric = "0.18.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-directory = "datapacks"
